# 配置端口
server:
  port: 8081
  servlet:
    context-path: /auth-service

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_service?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    defaultAutoCommit: false
    maxActive: 300
    maxIdle: 30
    maxWait: 10000
    minIdle: 0
    validationQuery: SELECT 1
    validationQueryTimeout: -1
    validationInterval: 34000
    testOnBorrow: true
    check:
    interval: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
